### ISSUE TITLE
Incorrect cert password in docker-compose.yaml

### ISSUE THREAD

**Issue by GFoley83** [meysamhadeli/Airline-Microservices#13]
The following error occurs when running the solution for the first time:

```js
  _____ _ _       _     _       ____                  _          
 |  ___| (_) __ _| |__ | |_    / ___|  ___ _ ____   _(_) ___ ___ 
 | |_  | | |/ _` | '_ \| __|___\___ \ / _ \ '__\ \ / / |/ __/ _ \
 |  _| | | | (_| | | | | ||_____|__) |  __/ |   \ V /| | (_|  __/
 |_|   |_|_|\__, |_| |_|\__|   |____/ \___|_|    \_/ |_|\___\___|
            |___/                                                


. . . 

Unhandled exception. System.Security.Cryptography.CryptographicException: The certificate data cannot be read with the provided password, the password may be incorrect.
 ---> System.Security.Cryptography.CryptographicException: The certificate data cannot be read with the provided password, the password may be incorrect.
   at Internal.Cryptography.Pal.UnixPkcs12Reader.VerifyAndDecrypt(ReadOnlySpan`1 password, ReadOnlyMemory`1 authSafeContents)
   at Internal.Cryptography.Pal.UnixPkcs12Reader.Decrypt(SafePasswordHandle password, Boolean ephemeralSpecified)
   --- End of inner exception stack trace ---
   at Internal.Cryptography.Pal.UnixPkcs12Reader.Decrypt(SafePasswordHandle password, Boolean ephemeralSpecified)
   at Internal.Cryptography.Pal.PkcsFormatReader.TryReadPkcs12(OpenSslPkcs12Reader pfx, SafePasswordHandle password, Boolean single, Boolean ephemeralSpecified, ICertificatePal& readPal, List`1& readCerts)
   at Internal.Cryptography.Pal.PkcsFormatReader.TryReadPkcs12(ReadOnlySpan`1 rawData, SafePasswordHandle password, Boolean single, Boolean ephemeralSpecified, ICertificatePal& readPal, List`1& readCerts, Exception& openSslException)
   at Internal.Cryptography.Pal.OpenSslX509CertificateReader.FromFile(String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(String fileName, String password)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Certificates.CertificateConfigLoader.LoadCertificate(CertificateConfig certInfo, String endpointName)
   at Microsoft.AspNetCore.Server.Kestrel.KestrelConfigurationLoader.LoadDefaultCert()
   at Microsoft.AspNetCore.Server.Kestrel.KestrelConfigurationLoader.Reload()
   at Microsoft.AspNetCore.Server.Kestrel.KestrelConfigurationLoader.Load()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Microsoft.AspNetCore.Builder.WebApplication.Run(String url)
   at Program.<Main>$(String[] args) in /app/Services/Airline.Flight/src/Flight.Api/Program.cs:line 66
```

The cause is the password you're using here:
```js
        - ASPNETCORE_Kestrel__Certificates__Default__Password=shieldh1988
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
```

I suggest either calling out that `shieldh1988` needs to be replaced with whatever password was set when dev certs were added, or, add some explicit instructions for setting the dev cert password:
```bash
dotnet dev-certs https -ep %USERPROFILE%\.aspnet\https\aspnetapp.pfx -p { password here }
dotnet dev-certs https --trust
```
https://docs.microsoft.com/en-us/aspnet/core/security/docker-compose-https?view=aspnetcore-6.0#starting-a-container-with-https-support-using-docker-compose

Also side note, these settings in your readme are incorrect:
``` bash
docker-compose -f ./deployments/Infrastructure-docker-compose.yaml up -d
docker-compose -f ./deployments/docker-compose.yaml up -d
```

They should be:
``` bash
docker-compose -f ./deployments/docker-compose/Infrastructure-docker-compose.yaml up -d
docker-compose -f ./deployments/docker-compose/docker-compose.yaml up -d
```

**Comment by meysamhadeli** [comment]
Thanks for mention these problems. I fixed the issues. And add doc for use `SSL` in project base on Microsoft docs.
